[project]
name = 'clarity-basics'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.clarity-basics]
path = 'contracts/clarity-basics.clar'
clarity_version = 2
epoch = 2.5

[contracts.clarity-basics-iii]
path = 'contracts/clarity-basics-iii.clar'
clarity_version = 2
epoch = 2.5

[contracts.clarity-basics-iv]
path = 'contracts/clarity-basics-iv.clar'
clarity_version = 2
epoch = 2.5

[contracts.community-hello-world]
path = 'contracts/community-hello-world.clar'
clarity_version = 2
epoch = 2.5

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
